"""
A set of functions to read and write pscf input and output files from data generated by the models in this codebase.

"""

import numpy as np

from .simulation_io import SimulationData

_CRYSTAL_SYSTEMS = {1: "lamellar", 2: "rectangular", 3: "orthorhombic"}


def write_C_RGRID_from_array(
    filepath: str,
    fields: np.ndarray,
    mesh: tuple[int, int, int],
    cell_params: list[float],
    fmt: str = "18.11e",
) -> None:
    """
    Write a pscfpp r-grid field file. The cell is always orthorhombic in my RPA code, so need 3 lattice parameters. No symmetry group is applied/assumed.
    Parameters
    ----------
    filepath : str
        Output file path.
    fields : np.ndarray, shape (n_monomer, Nx, Ny, Nz)
        Field values on the real-space mesh.  Can be omega-fields
        (chemical potentials) or c-fields (concentrations).
    mesh : tuple of int
        (Nx, Ny, Nz) grid dimensions.  Must match fields.shape[1:].
    fmt : str, default "18.11e"
        Format specifier for floating-point values in the data block.
    """
    fields = np.asarray(fields, dtype=np.float64)
    n_monomer = fields.shape[0]

    # --- validation ---
    if fields.shape[1:] != tuple(mesh):
        raise ValueError(f"Field shape {fields.shape[1:]} does not match mesh {mesh}")

    # --- write header ---
    with open(filepath, "w") as f:
        f.write("format  1  0\n")
        f.write("dim\n")
        f.write("               3\n")
        f.write("crystal_system\n")
        f.write("          orthorhombic\n")
        f.write("N_cell_param\n")
        f.write("               3\n")
        f.write("cell_param   \n")

        # cell parameters on one line, space-separated
        param_str = "   ".join(f"{p:{fmt}}" for p in cell_params)
        f.write(f"   {param_str}\n")

        # f.write("group_name\n") # group_name should be optional, check this later
        # f.write("          P1\n")
        f.write("N_monomer\n")
        f.write(f"               {n_monomer}\n")
        f.write("mesh\n")
        f.write(f"              {mesh[0]:5d}{mesh[1]:5d}{mesh[2]:5d}\n")

        # --- write data block ---
        # Iterate in C-order: ix slowest, iz fastest
        for ix in range(mesh[0]):
            for iy in range(mesh[1]):
                for iz in range(mesh[2]):
                    vals = "   ".join(
                        f"{fields[m, ix, iy, iz]:{fmt}}" for m in range(n_monomer)
                    )
                    f.write(f"   {vals}\n")


def write_param_file(filepath: str, sim: SimulationData) -> None:
    """
    Write a pscfpp parameter file from a SimulationData object.

    The RPA code always produces a single linear multiblock copolymer
    melt on a rectangular grid with P_1 symmetry.  This function
    hard-codes those invariants and derives everything else from *sim*.

    Parameters
    ----------
    filepath : str
        Output file path.
    sim : SimulationData
        Simulation data container with system definition.
    """
    n_mon = sim.n_components
    chi = np.asarray(sim.chi_matrix)
    crystal_system = _CRYSTAL_SYSTEMS[sim.ndim]

    with open(filepath, "w") as f:
        f.write("System{\n")

        # --- Mixture block ---
        f.write("  Mixture{\n")
        f.write(f"    nMonomer  {n_mon}\n")
        f.write("    monomers[\n")
        for _ in range(n_mon):
            f.write(f"      {sim.b:.10e}\n")
        f.write("    ]\n")

        f.write("    nPolymer  1\n")
        f.write("    Polymer{\n")
        f.write(f"      nBlock   {n_mon}\n")
        f.write(f"      nVertex  {n_mon + 1}\n")
        f.write("      blocks[\n")
        for i in range(n_mon):
            f.write(f"        {i}  {i}  {i + 1}  {sim.block_fractions[i]:.10e}\n")
        f.write("      ]\n")
        f.write(f"      phi  {1.0:.10e}\n")
        f.write("    }\n")

        f.write("  }\n")

        # --- ChiInteraction block ---
        f.write("  ChiInteraction{\n")
        f.write("    chi(\n")
        for i in range(n_mon):
            for j in range(i, n_mon):
                f.write(f"      {i}  {j}  {chi[i, j]:.10e}\n")
        f.write("    )\n")
        f.write("  }\n")

        # --- Domain block ---
        f.write("  Domain{\n")
        mesh_str = "".join(f"{m:6d}" for m in sim.grid_shape)
        f.write(f"    mesh    {mesh_str}\n")
        f.write(f"    lattice    {crystal_system}\n")
        # f.write("    groupName  P_1\n") # I think groupName is optional, let's not add it to avoid needing symmetry
        f.write("  }\n")

        # --- AmIterator block ---
        f.write("  AmIterator{\n")
        f.write("    maxItr      200\n")
        f.write("    epsilon     1.00e-08\n")
        f.write("    maxHist     50\n")
        f.write("    isFlexible  0\n")
        f.write("  }\n")

        f.write("}\n")


def write_command_file(filepath: str) -> None:
    """
    Write a pscfpp command file for the standard RPA-to-SCFT workflow.

    Reads a concentration field produced by the RPA code, estimates
    initial omega fields, iterates to self-consistency, and writes the
    converged concentration field.

    Parameters
    ----------
    filepath : str
        Output file path.
    """
    with open(filepath, "w") as f:
        f.write("READ_C_RGRID       in/c.rf\n")
        f.write("ESTIMATE_W_FROM_C\n")
        f.write("ITERATE\n")
        f.write("WRITE_C_RGRID      out/c.rf\n")
        f.write("FINISH\n")
